# -*- coding: utf-8 -*-
#!/usr/bin/env python

# Process XML file generated by GestIB app, compares with data generated year by year
# Author: Bartomeu Vives, based on https://www.josedomingo.org/pledin/2015/01/trabajar-con-ficheros-xml-desde-python_2/

# python gestib2gpuntis.py -g ExportacioDadesHoraris.xml ExportacioDadesHoraris2.xml -a
# URL Fitxer gestib: https://www3.caib.es/xestib/alumnat/importacio/exportacioDadesCentre.xml?codiAny=2018

# from __future__ import print_function

import xml.etree.ElementTree as ET
import argparse

# PARSE SECTION ----------------------------------------------------------------------------------------
parser = argparse.ArgumentParser(description='Gestib XML comparator.')
parser.add_argument("-g", "--gestib", nargs=2, required=True,
                    help="XML Generated by GestIB application")

group = parser.add_mutually_exclusive_group(required=True)
group.add_argument("-v", "--view", action="store_true", help="View changes")
group.add_argument("-a", "--apply", action="store_true", help="Apply changes in 'output file'")

args = parser.parse_args()

# XML scope
XMLSCOPE = "MATERIES/MATERIA"

# FUNCTION DECLARATION SECTION -------------------------------------------------------------------------
def applicator(arxiuOrigen, arxiuDesti):
	print('Loading XML data from [' + arxiuDesti + '], comparing to [' + arxiuOrigen + '] for applying')
	
	arbreD = ET.parse(arxiuDesti)
	arrelD = arbreD.getroot()
	materiesD = arrelD.findall(XMLSCOPE)
    
	arbreO = ET.parse(arxiuOrigen)
	arrelO = arbreO.getroot()
	materiesO = arrelO.findall(XMLSCOPE)
	
	i = 0
	for matD in materiesD:
		j = 0
		for matO in materiesO:
			# print(materiesD[i].get("codi") + ':' + materiesD[i].get("curta") + ' - ' + materiesO[j].get("codi") +' :'+ materiesO[j].get("curta") )
			if materiesD[i].get("curta") == materiesO[j].get("curta"):
				if materiesD[i].get("codi") != materiesO[j].get("codi"):
					materiesD[i].set("codi",materiesO[j].get("codi"))
					break
				break
			j += 1
		i += 1

	print('File \'output.xml\' created ')
	arbreD.write('output.xml',encoding="UTF-8",xml_declaration=True)

def carregator(nomArxiu):
	# carrega un XML a una variable de tipus conjunt
	print('Carregant l\'arxiu XML ... ' + nomArxiu)
	xmlmateries = {}
	tree = ET.parse(nomArxiu)
	root = tree.getroot()
	cont = 0
    
	materies = root.find("MATERIES")
	for materia in materies:
		cont+=1
		xmlmateries[materia.get("codi")] = {
											'curta': materia.get("curta"),
											'descripcio': materia.get("descripcio")
											}
	print('{0} materies carregades'.format(cont))
	return xmlmateries
	
def comparator(materiesO, materiesD):
	# print('Loading XML data from [' + arxiuDesti + '], compares to [' + arxiuOrigen + '] for viewing')
	# comparar materiesO amb materiesD tractat mitjançant variables tipus conjunt
	xmlmateries = {}
	for mD in materiesD:
		"""
		print(mO)
		print(materiesO[mO])
		print(materiesO[mO].get('curta'))
		print(materiesO[mO].get('descripcio'))

		# cercam materiaDesti a materiaOrigen
		trobat = False
		try:
			# existeix i els codis son iguals ?
			if (materiesD[mD].get('curta') == materiesO[mD].get('curta')):
				if (materies
		except KeyError:
			print("No Name exist!")
		"""
		trobat = False
		for mO in materiesO:
			if (materiesD[mD].get('curta') == materiesO[mO].get('curta')):
				trobat = True
				if (mD != mO):
					xmlmateries[mD] = { 'curta': materiesD[mD].get('curta'),
										'descripcio': materiesD[mD].get('descripcio')
									  }
				else:
					xmlmateries[mO] = { 'curta': materiesD[mD].get('curta'),
										'descripcio': materiesD[mD].get('descripcio')
									  }

		# sino es troba
		if not trobat:
			xmlmateries[mD] = { 'curta': materiesD[mD].get('curta'),
								'descripcio': materiesD[mD].get('descripcio')
							  }
			# print(materiesD[mD].get('curta') + ' no es troba')
	return xmlmateries

def viewator(arxiuOrigen, arxiuDesti):
	print('Arxiu ORIGEN: ' + arxiuOrigen)
	xmlmateriesORIGEN = carregator(arxiuOrigen)
	print('Arxiu DESTI: ' + arxiuDesti)
	xmlmateriesDESTI = carregator(arxiuDesti)
	# totes
	print('ORIGEN --------------------------')
	print(xmlmateriesORIGEN)
	print('DESTI  --------------------------')
	print(xmlmateriesDESTI)
	# cada una d'elles
	xmlmateries = comparator(xmlmateriesORIGEN, xmlmateriesDESTI)
	print('COMPARACIÓ --------------------------')
	print(xmlmateries)

# STARTING UP ------------------------------------------------------------------------------------
if __name__ == '__main__':
	if args.apply:
		applicator(args.gestib[0], args.gestib[1])
	elif args.view:
		viewator(args.gestib[0], args.gestib[1])

